### ISSUE TITLE
Файлы

### ISSUE THREAD

**Issue by paulin-mipt** [ceasminog/Python_Is_The_Best#3]
Давайте разнесем классы по файлам, 300 строк кода -- это уже очень много. Необязательно создавать файл для каждого класса, хотя бы все в один

**Comment by ceasminog** [comment]
Разделила на 3 файла:
графика, классы объектов и внутренний функционал
+ файл для чтения

**Comment by ceasminog** [comment]
ой, случайно закрыла issue

**Comment by ceasminog** [comment]
(

**Comment by paulin-mipt** [comment]
Во-первых, если очень хочется, то есть функция reopen issue, а во-вторых, я не против, чтобы вы их сами закрывали :)
