### ISSUE TITLE
def __str__

### ISSUE THREAD

**Issue by paulin-mipt** [ceasminog/Python_Is_The_Best#6]
https://github.com/ceasminog/Python_Is_The_Best/blob/46a79ef46de09d68cba0fae84bc3743087df64c4/Creatures.py#L46

Давайте поменяем функцию PrintMe на дефолтную magic __str__, когда она реализована, то можно делать print(obj), str(obj), да и вообще это круто.

P.S. Кодстайл в названиях методов! IsAlive -> is_alive и т.д.

**Comment by ceasminog** [comment]
Так как я пользуюсь pyGame, то вывод на экран там замысловатый
 text = font.render(graphic_field[i], True, (255, 193, 7))
        screen.blit(text, [20, 20 + 40 * i])
Реализовала __str__, но пользуюсь им напрямую, не через print, т.к. в консоль ничего не вывожу.
